version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    image: movri_web
    env_file: .env.local
  worker:
    image: movri_web
    env_file: .env.local
    command: bundle exec rake jobs:work
    depends_on:
      - web
  memcached:
    image: memcached:latest
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root