version: '2'
services:
  web:
    build: .
    dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    image: movri_web
    env_file: .env.local
  worker:
    image: movri_web
    env_file: .env.local
    command: bundle exec rake jobs:work
    depends_on:
      - web
  memcached:
    image: memcached:latest