version: '2'
services:
  api:
    build: .
    ports:
      - "8085:8085"
    environment:
      - DB_PORT=3306
      - DB_HOST=db
    command: ["./docker/startup.sh"]
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=harmony-root
    volumes:
      - ~/.sharetribe/harmony-mysql-data:/var/lib/mysql
    ports:
      - "13306:3306"
